### ISSUE TITLE
Training data acquisition

### ISSUE THREAD

**Issue by DerekBin** [JinLabBioinfo/DeepLoop#5]
If I want to train the model, how do I get the training data you provide?

**Comment by shanshan950** [comment]
Try `wget --no-check-certificate https://hiview.case.edu/ssz20/tmp.HiCorr.ref/DeepLoop_trainingData.tar.gz`. Check the README file after you unzip it.

**Comment by PhoenixMWJ** [comment]
How do we get pooled data in the process of combining replicates？ Not found in the above link. Thank you.
