### ISSUE TITLE
Convert hg19 to hg38

### ISSUE THREAD

**Issue by AssumeAssume** [JinLabBioinfo/DeepLoop#6]
Hello,
DeepLoop really helps our work. But it gives the results using hg19 coordinates.
I wonder if there is anything I can do to convert the `cool` file from hg19 to hg38 ? Or could DeepLoop  gives hg38 results?
Thank you

**Comment by JinLabBioinfo** [comment]
In the HiCorr GitHub page, towards the bottom of the main page, we have an instruction on how to generate reference files for HiCorr. You may follow the example to generate reference files for hg38. This will allow you to analyze hg38.
